name: AoC check
on: [push]
jobs:
  aoc-all:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ runner.os }} - ${{ github.event_name }} to repo ${{ github.repository }} branch ${{ github.ref }} workspace ${{ github.workspace }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          yarn
      - env:
          AOC_COOKIE: ${{ secrets.aoc_cookie }}
        run: |
          yarn solve 0 1 2015
      - run: |
          yarn test 2015
      - run: echo "status ${{ job.status }}"
